[tool.poetry]
name = "tsi-project"
version = "0.1.0"
description = "TSI Project"
authors = [
    "Marc Partensky <marc.partensky@gmail.com>",
    "Valentin Colin <valentin.colin78@gmail.com>"
    ]
readme = "README.md"
packages = [{include = "tsi_project"}]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
