[tool.poetry]
name = "tsi-project"
version = "0.1.0"
description = "TSI Project"
authors = ["Marc Partensky <marc.partensky@gmail.com>"]
readme = "README.md"
packages = [{include = "tsi_project"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
neovim = "^0.3.1"
pyright = "^1.1.294"
black = "^23.1.0"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
